---
site_name: traceroute.org
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tracking
    # - navigation.tabs
    # - navigation.tabs.sticky
repo_url: https://github.com/reneluria/autowebsite
repo_name: autowebsite
