# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially orfor mdfile in *md; do page=${mdfile%.md}; echo $mdfile ${page}.html; done in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: node:lts

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: npm install
      run: npm install

    # Runs a set of commands using the runners shell
    - name: convert markdown files
      run: |
        for mdfile in *md; do
          page=${mdfile%.md};
          echo "Converting $page"
          node convert.js $mdfile > ${page}.html
        done
