# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm install
      - name: Generate pages
        run: |
          mkdir html
          for mdfile in *md; do
            page=${mdfile%.md}
            echo $page
            node convert.js $mdfile > html/${page}.html
          done
      - name: Upload result
        uses: actions/upload-artifact@v1
        with:
          name: html
          path: html

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download result of build setp
        uses: actions/download-artifact@v1
        with:
          name: html
      - uses: actions/checkout@v2
      - name: Setup SSH
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan kunk.ftp.infomaniak.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
      - name: Some task that fetches dependencies
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          scp html/* kunk_github@kunk.ftp.infomaniak.com:web/website/

